### ISSUE TITLE
Fatal Error em throw new RedeException

### ISSUE THREAD

**Issue by marcosclbr** [DevelopersRede/erede-php#1]
Está ocorrendo erro fatal quando é retornado um codigo de status > 400 conforme abaixo o erro.
Desta maneira não consigo tratar o retorno da rede que neste caso é "cod: 171 - Operation not allowed for this transaction."

Será que está faltando algo em meu código? Essa função "throw new RedeException" tem alguma dependência que não estou vendo?

Fatal error: Uncaught exception 'Rede\Exception\RedeException' with message 'Operation not allowed for this transaction.' in /home/resen685/public_html/integrarRede/vendor/developersrede/erede-php/src/Rede/Service/AbstractTransactionsService.php:80 Stack trace: #0 /home/resen685/public_html/integrarRede/vendor/developersrede/erede-php/src/Rede/Service/AbstractService.php(117): Rede\Service\AbstractTransactionsService->parseResponse('{"returnCode":"...', 422) #1 /home/resen685/public_html/integrarRede/vendor/developersrede/erede-php/src/Rede/Service/CaptureTransactionService.php(15): Rede\Service\AbstractService->sendRequest('{"amount":2099}', 'PUT') #2 /home/resen685/public_html/integrarRede/vendor/developersrede/erede-php/src/Rede/eRede.php(59): Rede\Service\CaptureTransactionService->execute() #3 /home/resen685/public_html/integrarRede/index.php(144): Rede\eRede->capture(Object(Rede\Transaction)) #4 {main} thrown in /home/resen685/public_html/integrarRede/vendor/developersrede/erede-php/src/Rede/Service/AbstractTransactionsService.php on line 80

**Comment by netojoaobatista** [comment]
@marcosclbr, quando algo diferente é retornado pela API, o SDK lança uma exceção; para lidar com isso, basta contornar seu código com um `try {} catch`. A exceção disparada é uma `Rede\Exception\RedeException`, então só fazer: 

```php
try {
//...
// seu código aqui
} catch (\Rede\Exception\RedeException $e) {
   echo $e->getMessage();
}
```
