### ISSUE TITLE
Problemas com Unicode ao enviar Transações

### ISSUE THREAD

**Issue by davicrystal** [DevelopersRede/erede-php#10]
Percebi que ao enviar transações com caracteres acentuados o SDK passou a gerar um erro, então realizei algumas requisições diretamente via curl para API usando o mesmo json gerado pelo SDK e percebi que a API e.Rede não aceita caracteres formatados com Unicode. Portanto acredito que seria bacana se SDK, ao se gerar o json, "escapar" o Unicode e manter os caracteres UTF-8, nesse caso, por exemplo, a linha:

https://github.com/DevelopersRede/erede-php/blob/8826e37f58d0e98e1aaacb33bfbe843105d60a67/src/Rede/Service/AbstractTransactionsService.php#L43

Deveria ser algo como:

```
    public function execute()
    {
        return $this->sendRequest(json_encode($this->transaction, JSON_UNESCAPED_UNICODE), AbstractService::POST);
    }
```

**Comment by netojoaobatista** [comment]
> o SDK passou a gerar um erro,

Erro?

**Comment by davicrystal** [comment]
Olá @netojoaobatista ,

Para mim o SDK gerou um erro, pois por alguma razão, a exceção não foi pega pela linha abaixo:

https://github.com/DevelopersRede/erede-php/blob/8826e37f58d0e98e1aaacb33bfbe843105d60a67/src/Rede/Service/AbstractTransactionsService.php#L80

Como a resposta da API é um texto "Acces Denied" então ocorre um erro na seguinte linha

https://github.com/DevelopersRede/erede-php/blob/8826e37f58d0e98e1aaacb33bfbe843105d60a67/src/Rede/Transaction.php#L384

**Comment by netojoaobatista** [comment]
Exatamente, qual a mensagem de erro? Precisamos dela para diagnosticar o problema.

**Comment by davicrystal** [comment]
O erro abaixo ocorre em meu ambiente ...

> get_object_vars() expects parameter 1 to be object, null given (/var/www/html/protected/components/gateways/ERede10/src/Rede/Transaction.php:384)

... Quando a API retorna o http status 403 e corpo com o texto  "Access Denied" ao se enviar no json da requisição algum caractere com Unicode, por exemplo:

```
{"kind":"credit","reference":"20181000000231","amount":1900,"cardHolderName":"Jo\u00e3o da Silva","cardNumber":"4235647728025682","expirationMonth":"1","expirationYear":"2020","securityCode":"123"}
```
Lembrando que o Unicode é gerado pela linha abaixo:

https://github.com/DevelopersRede/erede-php/blob/8826e37f58d0e98e1aaacb33bfbe843105d60a67/src/Rede/Service/AbstractTransactionsService.php#L43

**Comment by netojoaobatista** [comment]
Ok, vamos lá:

Temos duas questões aqui: a primeira é [a linha que faz uma comparação estrita com `false`](https://github.com/DevelopersRede/erede-php/blob/8826e37f58d0e98e1aaacb33bfbe843105d60a67/src/Rede/Transaction.php#L380), quando a comparação deveria ser com `NULL`: [http://php.net/manual/pt_BR/function.json-decode.php](http://php.net/manual/pt_BR/function.json-decode.php).

A segunda é o envio de um *João* no `cardHolderName`; esse campo é o nome impresso no cartão e não é utilizado caracteres acentuados; assim, basta remover o acento que funcionará.

Quanto ao `if ($properties === false)`, mudar para `if (is_null($properties))` resolve o problema.
