### ISSUE TITLE
reference: Order number already exists em Sandbox para qualquer valor no campo reference

### ISSUE THREAD

**Issue by gilbertoalbino** [DevelopersRede/erede-php#12]
Olá, estou tentando realizar transações no Sandbox, mas retorna o codigo de integração 42 o tempo todo.
Mesmo que eu coloque strings como "er5bd74dc2985f08" ele retorna o mesmo erro, tornando impraticável utilizar o Sandbox.
Curiosamente, nos primeiros dias em que tive contato com a integração via SDK, eu fiz dezenas de transações no Sandbox com o campo "reference" definido como "1".

**Comment by netojoaobatista** [comment]
>  eu fiz dezenas de transações no Sandbox com o campo "reference" definido como "1".

Exatamente. Se você já enviou um pedido com o `reference` igual a 1, você não pode enviar mais. Como sugestão, concatene um valor progressivo, como a função `time()`, nos seus testes.

**Comment by gilbertoalbino** [comment]
Sim, acho que você não entendeu o que eu disse.

Eu fiz dezenas de transações no Sandbox com o "reference" marcado sempre como "1" no Postman, e todas passaram.

No entanto, a partir de hoje, eu não consigo mais fazer qualquer transação no Sandbox, pois qualquer string alfanumérica que eu use retorna o código 42.

Como exemplo, se eu usar um Hash como "er5bd74dc2985f08", o Sandbox não aceita.
Fiz um teste agora com "1540844039" (echo do time()) e retornou o mesmo código.

Estou o dia todo já nesse dilema.

**Comment by netojoaobatista** [comment]
> Eu fiz dezenas de transações no Sandbox com o "reference" marcado sempre como "1" no Postman, e todas passaram.

Isso jamais deveria funcionar.

> Como exemplo, se eu usar um Hash como "er5bd74dc2985f08", o Sandbox não aceita.
> Fiz um teste agora com "1540844039" (echo do time()) e retornou o mesmo código.

Por favor, executando o código abaixo, qual a saída?

```php
<?php
require 'vendor/autoload.php';

$pv = 'COLOQUE_SEU_PV_AQUI';
$token = 'COLOQUE_SEU_TOKEN_AQUI';
$environment = \Rede\Environment::sandbox();

// Configuração da loja
$store = new \Rede\Store($pv, $token, $environment);

// Transação que será autorizada
$transaction = (new \Rede\Transaction(20, 'pedido' . time()))->creditCard(
    '5448280000000007',
    '235',
    '12',
    '2020',
    'John Snow'
);

// Autoriza a transação
$transaction = (new \Rede\eRede($store))->create($transaction);

printf("Rede[%s]: %s\n", $transaction->getReturnCode(), $transaction->getReturnMessage());

if ($transaction->getReturnCode() == '00') {
    printf("Transação autorizada com sucesso; tid=%s\n", $transaction->getTid());
}
```

**Comment by gilbertoalbino** [comment]
Usando 'pedido'.time():
Rede[00]: Success. Transação autorizada com sucesso; tid=10218102822150803032 Not found!

Rodei o script puro sem estar integrado na aplicação.
Vou inspecionar pra ver onde posso estar comendo bola.

**Comment by netojoaobatista** [comment]
@gilbertoalbino, no [ambiente do desenvolvedor da Rede](https://www.userede.com.br/desenvolvedores/pt/entrar), no mesmo lugar onde você gerou seu `PV` e `Token`, você  consegue ver todas as requisições feitas - em todo o período. Após acessar o ambiente dos desenvolvedores, vá até sua loja de testes e escolha a opção **detalhes**; vai aparecer uma área como a abaixo:

![captura de tela de 2018-10-29 18-26-53](https://user-images.githubusercontent.com/273586/47681454-409fc000-dba8-11e8-996c-27fe2039887a.png)

Informe as datas inicial e final que deseja pesquisar e clique em **pesquisar**; aí na listagem, só clicar na requisição para você ver exatamente o que enviou e o que recebeu:

![captura de tela de 2018-10-29 18-28-08](https://user-images.githubusercontent.com/273586/47681521-7775d600-dba8-11e8-80a9-37287d187c68.png)

**Comment by gilbertoalbino** [comment]
Obrigado. Refiz toda a integração e voltou a funcionar... Mas nao achei aonde comi bola.
