### ISSUE TITLE
sem retorno

### ISSUE THREAD

**Issue by frital** [DevelopersRede/erede-php#15]
Prezados, primeiramente, parabéns pela documentação!! Excelente.
Sem mencionar a grande quantidade de SDK's! Parabéns!!!!

Antes que eu esqueça, o site (developers) está com tempos de resposta muito alta. Por exemplo, ao efetuar o login, ou pedir para exibir as lojas, enfim, muito lento, desde o dia em que fiz o cadastro (dia 13/02/2019).
Ah, ainda sugiro atualizar a documentação informando que o terceiro parâmetro para objetos "Store" deve ser o ambiente, assim como, na minha humilde opinião, acho que o default (quando omitido) deveria ser sandbox. Mas, sem problemas. (Para ajudar, tomei a liberdade de fazer um pull request, caso concorde) =)

Vamos ao problema:
Estou no modo sandbox, e somente tenho retorno da api se algo estiver errado com os dados de PV ou token (aí recebo o "Affiliation: Invalid parameter format" ou "Token: Invalid token.").
Caso estes dados estejam corretos, não recebo mais retorno a api. O que eu poderia estar fazendo errado? (ou será que teria haver com a lentidão que mencionei préviamente?)
Muito obrigado por antecipação, e abaixo trecho do meu código:

`
        $store = new Store(env('E_REDE_PV'),env('E_REDE_TOKEN'), Environment::sandbox());

        $transaction = new Transaction();
        $transaction->setReference($idVenda);
        $transaction->setAmount($valorTotal);
        $transaction->setSoftDescriptor($produto);
        $transaction->capture(true);
        $transaction->setCard($cardNumber, $securityCode, $expirationMonth, $expirationYear, $cardHolderName, 'credit');
        if ($installments != null)
            $transaction->setInstallments($installments);

        $eRede = new eRede($store);

        $retorno  = null;

        try {
            $retorno = $eRede->create($transaction);
        } catch (RedeException $ex) {
            $retorno = $ex->getMessage();
        }

        print_r($retorno);`

**Comment by netojoaobatista** [comment]
> Antes que eu esqueça, o site (developers) está com tempos de resposta muito alta.

Também percebi isso ao fazer login, mas a API em si tem um tempo de resposta razoável. De qualquer forma, vou repassar essa informação porque também percebi isso.

> ou será que teria haver com a lentidão que mencionei préviamente?

Você tem algum log? Porque eu executei um teste aqui e tive uma resposta como o esperado. Abaixo o meu teste:

```php
<?php
require 'vendor/autoload.php';

$pv = '{PV}';
$token = '{TOKEN}';
$environment = \Rede\Environment::sandbox();

// Configuração da loja
$store = new \Rede\Store($pv, $token, $environment);

// Transação que será autorizada
$transaction = (new \Rede\Transaction(20, 'pedido' . time()))->creditCard(
    '5448280000000007',
    '235',
    '12',
    '2020',
    'John Snow'
);

// Autoriza a transação
$transaction = (new \Rede\eRede($store))->create($transaction);

printf('Rede[%s]: %s', $transaction->getReturnCode(), $transaction->getReturnMessage());

if ($transaction->getReturnCode() == '00') {
    printf("Transação autorizada com sucesso; tid=%s\n", $transaction->getTid());
}
```

A saída é:

```
Rede[00]: Success.Transação autorizada com sucesso; tid=...
```
