### ISSUE TITLE
Integração de Debito

### ISSUE THREAD

**Issue by edsonrbispo** [DevelopersRede/erede-php#20]
Olá,
poderia me explicar como faria a implementação da forma de debito, eu trabalho muito com o PagSeguro e lá ele tem a opção de selecionar o banco na loja virtual, no sistema rede é a mesma coisa? pois eu não achei nada que me explica-se a forma de integrar o debito na loja virtual.
Desculpe mais é a primeira vez que trabalho com a rede.
Agradeço

**Comment by netojoaobatista** [comment]
É igual a [autorizar uma trasação](https://github.com/DevelopersRede/erede-php#autorizando-uma-transa%C3%A7%C3%A3o), só que em vez de usar o `Transaction::creditCard`, você vai usar `Transaction::debitCard`.

**Comment by edsonrbispo** [comment]
Blz, agradeço!

**Comment by souzadavi** [comment]
Conseguiu transacionar em débito? Aqui pra mim da erro, não consegue transacionar, não tem autorização. Também no manual não encontrei informações sobre a autenticação do débito... No cartão de débito a Erede não precisa retornar com um URL para autenticação do cartão de débito?
