### ISSUE TITLE
Ajuda no E-rede

### ISSUE THREAD

**Issue by claudiomartinez123** [DevelopersRede/erede-php#21]
Olá amigo, estou implementando o e-rede em uma loja propria de um cliente em ASP classico.
É a primeira vez que trabalho com json, mas ja tenho toda a biblioteca.
Estou tendo apenas 1 dificuldade, para enviar o json, como faço para enviar os dados da afiliacao, que seria o pv e o toquem enquanto esta em desenvolvimento?
No corpo do json não aceita, na url do Post me retorna somente os dados que enviei.
Pode me ajudar?

**Comment by netojoaobatista** [comment]
Os `PV` e `Token` são usuário e senha que devem ser enviados para uma autenticação Http Basic: veja a [documentação](https://www.userede.com.br/desenvolvedores/pt/produto/e-Rede#documentacao-filiacao) na parte que trata da  filiação e token.

**Comment by claudiomartinez123** [comment]
consegui, obrigado.
