### ISSUE TITLE
Quantidade de Parcelas

### ISSUE THREAD

**Issue by CeltaCtba** [DevelopersRede/erede-php#22]
Onde é informado em quantas parcelas o cliente vai efetuar o pagamento.
Creio que deveria estar no json. "installments"

Liguei para  a Rede mas souberam informar...

**Comment by edson-nascimento** [comment]
> Onde é informado em quantas parcelas o cliente vai efetuar o pagamento.
> Creio que deveria estar no json. "installments"
> 
> Liguei para a Rede mas souberam informar...

O campo no json é 'installments' abaixo um exemplo de transação em 3x utilizando o sdk php

`$transaction->setInstallments(3);`

Se o Installments não for setado ele assume que será apenas uma parcela no crédito.

**Comment by CeltaCtba** [comment]
> > Onde é informado em quantas parcelas o cliente vai efetuar o pagamento.
> > Creio que deveria estar no json. "installments"
> > Liguei para a Rede mas souberam informar...
> 
> O campo no json é 'installments' abaixo um exemplo de transação em 3x utilizando o sdk php
> 
> `$transaction->setInstallments(3);`
> 
> Se o Installments não for setado ele assume que será apenas uma parcela no crédito.

Obrigado
