### ISSUE TITLE
Adicionar Item

### ISSUE THREAD

**Issue by edsonrbispo** [DevelopersRede/erede-php#23]
Olá, estou construindo um projeto de inscrição de curso, mas gostaria de na transação adicionar o curso contratado na transação, teria como adicionar um ou mais item na forma de "Autorizando uma transação".
Vi que tem na forma de autorização antifraude, mas são muitos dados do cliente e o sistema é bem simples, não solicitamos o endereço no cadastro apenas dados pessoais simples para identificação do mesmo. 
Agradeço

**Comment by thayronarrais** [comment]
Você pode criar ele de forma separada e depois inserir, veja o exemplo 

` 
$store = new \Rede\Store('PV', 'Token', \Rede\Environment::sandbox());
                    $cart = (new \Rede\Cart());
                    
                    foreach ($itens as $key => $item) {       
                            $itemCart = (new \Rede\Item($id,$quantidady,\Rede\Item::PHYSICAL));
                            $itemCart->setAmount($item->price);
                            $itemCart->setDescription($item->name);
                            $cart->addItem($itemCart);
                        }
                    }

                 
                    $transaction = (new \Rede\Transaction())->creditCard(
                        '5448280000000007',
                        '123',
                        '01',
                        '2020',
                        'John Snow'
                    );

                    $transaction->setCart($cart);`
