### ISSUE TITLE
Tokenização de Cartões

### ISSUE THREAD

**Issue by NettoPassaro** [DevelopersRede/erede-php#25]
Olá!

Alguém sabe me informar se na Rede eu consigo fazer a Tokenização de Cartões?

Utilizo essa função na Cielo, e gostaria de usar também na Rede.

Lendo o manual, vi que a Rede oferece um serviço de Carteira Digital, mas acredito que não seja a mesma coisa, pois eles comentam que precisa ser contratado por bandeira.

Obrigado!

**Comment by robersonfaria** [comment]
Também gostaria de utilizar essa opção, mas não encontrei nada na documentação também

**Comment by diogodourado** [comment]
@NettoPassaro e @robersonfaria ... voces conseguiram? poderiam me dar uma luz/

**Comment by NettoPassaro** [comment]
@diogodourado Nada... O jeito é você armazenar os dados

**Comment by robersonfaria** [comment]
@NettoPassaro sério que armazena o dado? não é muito arriscado?

Por hora eu optei a pedir sempre os dados do cartão para o cliente.

**Comment by NettoPassaro** [comment]
@robersonfaria Sim, esse é o melhor procedimento.. porém, eu gostaria de usar para recorrência... Neste caso o cliente não iria acessar o site toda a vez.

**Comment by robersonfaria** [comment]
@NettoPassaro putz, entendi, realmente com recorrência ou não usa a rede ou guarda os dados, já tentou abrir um ticket na rede mesmo(não aqui no github)? Teve algum retorno deles sobre essa situação?
