### ISSUE TITLE
Sandbox aceitando Validade e CVV incorretos

### ISSUE THREAD

**Issue by pablovdsp** [DevelopersRede/erede-php#27]
Boa tarde.
Estou desenvolvendo um app, utilizando o sistema da rede, finalizando fui efetuar os testes de erro, CVV errado, data de validade errada, etc...
Porém, pelo que vi, ele aceita qualquer CVV e validade, quebrando meus testes de erro.
Alguma luz?
Obrigado.

**Comment by netojoaobatista** [comment]
O objetivo do SDK é facilitar a integração. Eventuais validações ficam sob responsabilidade do seu app.
