### ISSUE TITLE
Código da transações

### ISSUE THREAD

**Issue by roquesz** [DevelopersRede/erede-php#28]
Como consigo a lista de código das transações atualizados. No link abaixo estão faltando alguns como por exemplo o 101 e 106.
https://www.userede.com.br/pt-BR/Lists/Downloads/Attachments/104/e.Rede%20Manual%20%20%20API%20SOAP.pdf

**Comment by netojoaobatista** [comment]
https://www.userede.com.br/desenvolvedores/pt/produto/e-Rede#documentacao-retemissor
