### ISSUE TITLE
Modo sandbox

### ISSUE THREAD

**Issue by ggiovanini** [DevelopersRede/erede-php#3]
Como faço para usar no modo sandbox?
Me parece que é esse meu problema estou tentando usar, porem ele só retorna: "Affiliation: Invalid parameter format.".
Pode me ajudar?

**Comment by netojoaobatista** [comment]
O terceiro parâmetro de `\Rede\Store` é um `\Rede\Environment`; se esse parâmetro for omitido, é assumido o ambiente de produção por padrão. Então basta informar o environment correto nesse parâmetro:

```php
// Ambiente de testes
$environment = \Rede\Environment::sandbox();

// Configuração da loja informando o ambiente
$store = new \Rede\Store('PV', 'TOKEN', $environment);
```

**Comment by ezequisanad** [comment]
boa noite galera 
>>>Softdescriptor: Invalid parameter size.<<<
esta certinho mais esta  retornando este erro no woocomerce!
