### ISSUE TITLE
Parse error: syntax error, unexpected T_OBJECT_OPERATOR in 

### ISSUE THREAD

**Issue by andymurakami** [DevelopersRede/erede-php#33]
Primeiro teste que fui fazer e já deu erro. O que estou fazendo errado ?

Parse error: syntax error, unexpected T_OBJECT_OPERATOR in /home/storage/d/8e/d4/duplloimpacto1/public_html/restrito/autorizacao.php on line 9

<?php
// Configuração da loja em modo produção
$store = new \Rede\Store('MEU_PV', 'MEU_TOKEN', \Rede\Environment::production());

// Configuração da loja em modo sandbox
// $store = new \Rede\Store('PV', 'TOKEN', \Rede\Environment::sandbox());

// Transação que será autorizada
$transaction = (new \Rede\Transaction(20.99, 'pedido' . time()))->creditCard(
    '5448280000000007',
    '235',
    '12',
    '2020',
    'John Snow'
);

// Autoriza a transação
$transaction = (new \Rede\eRede($store))->create($transaction);

if ($transaction->getReturnCode() == '00') {
    printf("Transação autorizada com sucesso; tid=%s\n", $transaction->getTid());
}

**Comment by rafaelmb** [comment]
Erro de sintaxe geralmente é uma dessas duas coisas: A primeira delas é um erro de sintaxe, faltou ponto e virgula etc. A segunda é um código php 7 rodando em php 5 (alguma coisa que o php não entenda).

**Comment by andymurakami** [comment]
Certo, Rafael, obrigado pela resposta.

Sim eu entendo que o erro de sintaxe refere-se a sintaxe, mas era no
arquivo e descobri que realment eo servidor tava com versão errada do PHP.

Para mim está bem nebuloso, pois não encontrei onde me retorna opcionais de
parcelas, calulos de juros e etc.  Apenas como autorizar e enviar a
transação.

Não existe algum módulo tipo um botão, como o pag seguro que ele
redireciona e de lá saem os calculos de parcelas, juros pro cliente e ai
confirma a venda ?

Muito obrigado, desculpe se parecer idiota, estou iniciando agora neste
ramo do ecommerce..

RGDS
Anderson






Em ter., 18 de fev. de 2020 às 14:01, Rafael Mena Barreto <
notifications@github.com> escreveu:

**Comment by rafaelmb** [comment]
Sobre o erro de versão (que ocasionou o erro de sintaxe) relaxa, acontece com todo mundo.  Sobre as especificidades da rede, eu preferia que alguém da rede se manifestasse mas que eu me lembre é assim mesmo, os itens que tu precisa (opção de parcelas, calculo de juro etc) são features de checkout, que a rede não possui.

**Comment by andymurakami** [comment]
Pois é, ai fica bem incompleto pra mim.

Obrigado, vamos aguardar se alguém da REDE se pronuncia ehhe






Em ter., 18 de fev. de 2020 às 17:54, Rafael Mena Barreto <
notifications@github.com> escreveu:
