### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Rede\Store' not found

### ISSUE THREAD

**Issue by MarceloSchemmer** [DevelopersRede/erede-php#36]
pessoal alguem pode me dar uma mão ? oque falta no cod para conseguir testar ? 
estou no php 7....
<?php
// Configuração da loja em modo produção
//$store = new \Rede\Store('PV', 'TOKEN', \Rede\Environment::production());

// Configuração da loja em modo sandbox
 $store = new \Rede\Store('123', 'abc123', \Rede\Environment::sandbox());

// Transação que será autorizada
$transaction = (new \Rede\Transaction(20.99, 'pedido' . time()))->creditCard(
    '5448280000000007',
    '235',
    '12',
    '2020',
    'John Snow'
);

// Autoriza a transação
$transaction = (new \Rede\eRede($store))->create($transaction);

if ($transaction->getReturnCode() == '00') {
    printf("Transação autorizada com sucesso; tid=%s\n", $transaction->getTid());
}

?>

**Comment by edson-nascimento** [comment]
Tem como colocar o código completo?
Você deu include no arquivo autoload do composer?

O exemplo que tem ali no readme funciona é só substituir o PV, TOKEN e escolher o ambiente.

```php
// Configuração da loja em modo produção
$store = new \Rede\Store('PV', 'TOKEN', \Rede\Environment::production());

// Configuração da loja em modo sandbox
// $store = new \Rede\Store('PV', 'TOKEN', \Rede\Environment::sandbox());

// Transação que será autorizada
$transaction = (new \Rede\Transaction(20.99, 'pedido' . time()))->creditCard(
    '5448280000000007',
    '235',
    '12',
    '2020',
    'John Snow'
);

// Autoriza a transação
$transaction = (new \Rede\eRede($store))->create($transaction);

if ($transaction->getReturnCode() == '00') {
    printf("Transação autorizada com sucesso; tid=%s\n", $transaction->getTid());
}
```

**Comment by MarceloSchemmer** [comment]
amigo, deu certo era somente isso que faltava mesmo, como faz um tempo que não mecho com php, tinha me esquecido de como utilizava o autoload.... apenas coloquei : require 'vendor/autoload.php';
