### ISSUE TITLE
URL de notificação  (callback)

### ISSUE THREAD

**Issue by julianohammerle** [DevelopersRede/erede-php#4]
Como faço para setar a url de notificação?

**Comment by netojoaobatista** [comment]
@julianohammerle: [URL de notificações](https://www.userede.com.br/desenvolvedores/pt/produto/e-Rede#documentacao-urlnot)

> ...acessando o portal da Rede em: menu e.Rede > Configurações > URL de notificações

O SDK não lida com notificações, apenas com a autorização, captura, cancelamento, consulta, etc. Mas você pode configurar sua URL de notificação no portal da Rede e, assim que recebê-las, implementar a lógica relacionada com seu negócio específico e/ou plataforma utilizada.

**Comment by gabrielrbarbosa** [comment]
Acredito que a pergunta foi relacionada a informar a URL de notificação para a transaction conforme implementado nesse método:
https://github.com/DevelopersRede/erede-php/blob/f9e6aa07b70d547e96bdd325ab2c3969e81efbbd/src/Rede/Transaction.php#L223
