### ISSUE TITLE
Sand Box

### ISSUE THREAD

**Issue by alvesfer** [DevelopersRede/erede-php#40]
Eu não sei colocar o sand box no meu site, alguém pode me ajudar? Sou iniciante e gostaria de aprender, mas não entendo, o suporte da rede pede que esteja pronto

**Comment by netojoaobatista** [comment]
@alvesfer, basta definir o ambiente na hora de criar a loja:

```php
// Isso irá usar o sandbox
$this->store = new Store($filiation, $token, Environment::sandbox());
```
