### ISSUE TITLE
Antifraud

### ISSUE THREAD

**Issue by rafanake** [DevelopersRede/erede-php#41]
Olá, vi que foi removida esta funcionalidade do SDK, exite algum lugar onde podemos encontrar os motivos e mais detalhes sobre o assunto?

**Comment by lguilherme44** [comment]
Olá, eu vi também, infelizmente!, justo agora estava implementando.

**Comment by netojoaobatista** [comment]
O antifraude está em processo de reanálise interna, por isso foi removido do SDK.
