### ISSUE TITLE
Fatal error: Uncaught RuntimeException: Curl error

### ISSUE THREAD

**Issue by gustavocb92** [DevelopersRede/erede-php#42]
Boa noite, estou com problemas na integração e o suporte solicitou a abertura dessa Issue.

Estou utilizando a api atualizada e as instruções do readme. Funcionava normalmente a função crédito e crédito parcelado, até que parou de funcionar e retorna o erro:

Fatal error: Uncaught RuntimeException: Curl error[7]: in /home/onaorg/public_html/vendor/developersrede/erede-php/src/Rede/Service/AbstractService.php:198 Stack trace: #0 /home/onaorg/public_html/vendor/developersrede/erede-php/src/Rede/Service/AbstractTransactionsService.php(47): Rede\Service\AbstractService->sendRequest('{"kind":"credit...', 'POST') #1 /home/onaorg/public_html/vendor/developersrede/erede-php/src/Rede/eRede.php(83): Rede\Service\AbstractTransactionsService->execute() #2 /home/onaorg/public_html/rede_teste.php(34): Rede\eRede->create(Object(Rede\Transaction)) #3 {main} thrown in /home/onaorg/public_html/vendor/developersrede/erede-php/src/Rede/Service/AbstractService.php on line 198

Testei em outro servidor e funciona normalmente. A versão do PHP do servidor que está com erro é: 7.3.22

Conseguem verificar qual configuração do servidor deve ser alterada?

Obrigado

**Comment by netojoaobatista** [comment]
@gustavocb92,

o erro 7 significa `CURLE_COULDNT_CONNECT`: [curl_errno](https://www.php.net/manual/pt_BR/function.curl-errno.php)

Isso, muito provavelmente, é causado por algum firewall impedindo a conexão externa.

:D
