### ISSUE TITLE
Como usar o softDescriptor

### ISSUE THREAD

**Issue by Vivatec** [DevelopersRede/erede-php#5]
Tudo bem?

Estou com dificuldade em encontrar informações sobre como usar o softDescriptor.
Coo ele deve ser usado?

Obrigado

**Comment by Stedile93** [comment]
Olá @Vivatec, tudo bem?

Mano, o softDescriptor serve pra definir o nome que vai aparecer na fatura do cartão de credito do cliente, conforme a própria documentação, "Frase personalizada que será impressa na fatura do portador".

Você pode adicionar ele ao objeto da sua transação dessa forma:
`$transaction->setSoftDescriptor('suaLoja');`

Aceita valores alfanuméricos e tem limite de 13 caracteres.

Espero ter ajudado, irmão!

Forte abraço!

**Comment by aCidcOde** [comment]
Só para adicionar uma informação para a thread. 
Você precisa habilitar essa função, senao vai receber o seguinte erro

 'returnCode' => '63', 'returnMessage' => 'Softdescriptor: Not enabled for this merchant.',
