### ISSUE TITLE
Ambiente de Testes fora do ar!

### ISSUE THREAD

**Issue by mateushck** [DevelopersRede/erede-php#51]
Ao realizar transações me retorna erro algum, e ao tentar criar uma loja nova, me retorna o erro. "Erro ao criar loja, entre em contato com a Rede." 
Alguém passando por isso também, alguma previsão de retorno?

**Comment by waberjr** [comment]
Mesma coisa!! 
Estamos parados com um desenvolvimento

![image](https://user-images.githubusercontent.com/50723052/127078445-1de53d2c-77b8-471b-8a9e-5a0f68748587.png)

**Comment by mateushck** [comment]
Liguei pro suporte da eRede, e incrivelmente, eles falaram que dava pra testar em produção. 
Que o ambiente de testes era ruim mesmo, mas iam abrir um chamado para o setor responsável.
Haha

**Comment by waberjr** [comment]
Uai como assim kkkkkk se eles disponibilizarem um cartão é tranquilo kkkkk

**Comment by RedeEc** [comment]
O endpoint original do ambiente sandbox está indisponível no momento. Para utilização do ambiente sandbox, alterem o endpoint no arquivo Environment (linha 10) para: https://sandbox-erede.useredecloud.com.br
Caso não estejam conseguindo criar uma loja no portal do desenvolvedor, utilizem paliativamente o PV 10007442 e Token 854fbef128a844d6a20300dc86dcaa94
