### ISSUE TITLE
Método Mage::log impede a execução da transação

### ISSUE THREAD

**Issue by davicrystal** [DevelopersRede/erede-php#6]
O SDK não funciona em cenários onde não se utiliza Magento pois o método **sendRequest** sempre invoca o método **\Mage::log**

https://github.com/DevelopersRede/erede-php/blob/5862ba6d64e83759c5aeb0c4393b507f89bf86cf/src/Rede/Service/AbstractService.php#L114

**Comment by netojoaobatista** [comment]
@davicrystal, vi seu PR, mas nesse caso, o `Mage::log` é inadequado porque ele é o log do Magento. Em vez dele, foi utilizado a `Psr\Log\LoggerInterface` para abstrair o log e a implementação padrão ficou por conta do `Monolog\Logger`. Dessa forma, é possível variar a implementação padrão do `Monolog` para uma implementação específica para o Magento.

Só faça um `composer update` aí e veja se está tudo okay.

**Comment by davicrystal** [comment]
@netojoaobatista Antes gostaria de dar uma sugestão. Não seria melhor deixar a critério do desenvolvedor a forma que ele deseja criar os logs? Por exemplo, no meu caso, eu não desejo utilizar o monolog pois seria mais um componente que deveria passar por uma revisão/homologação sempre que atualizado. Em minha opinião o SDK, como os anteriores, deveria focar-se na integração com a operadora sem necessidade de bibliotecas de terceiros, porque reduzindo as dependências, temos mais segurança e a liberdade para os desenvolvedores utilizarem as bibliotecas que desejarem em seu ambiente de produção.

**Comment by davicrystal** [comment]
@netojoaobatista Verificando sua atualização vejo que você está dando a "liberdade" entre escolher entre duas bibliotecas a Psr\Log ou Monolog.  :(

Na minha humilde opinião, com isso, você tirou a versatilidade do SDK porque **dependendo do contexto**, além de ser obrigado a inserir em seu projeto uma das 2 bibliotecas, o desenvolvedor será  obrigado tb a implementar a abstração "LoggerInterface". Arrisco dizer que muitos desenvolvedores terão dificuldade caso não utilizem uma framework ou em aplicações "Legado".

Novamente, sob meu ponto de vista, o SDK deveria ter foco a comunicação com a operadora, e os logs deveriam ficar a critério do desenvolvedor e aplicados apenas na camada da aplicação principal.

Ainda considerando suas atualizações, caso decida manter a questão dos logs, sugiro atualizar os exemplos, pois se eu não estou enganado, eles não irão funcionar caso o desenvolvedor instancie a classe **eRede** sem uma variável com a instância de **LoggerInterface**, exemplo:

**Não funciona**
```
// Autoriza a transação
$transaction = (new \Rede\eRede($store))->create($transaction); 
```

**Porque:**

https://github.com/DevelopersRede/erede-php/blob/0685daed7fe3e25be4664c3ec8f9dc751c00d296/src/Rede/eRede.php#L33

**Comment by netojoaobatista** [comment]
@davicrystal, `Psr\Log\LoggerInterface` é uma interface, não uma biblioteca. As PSR são proposições de coding standards da comunidade. No caso, a `LoggerInterface` é a [PSR 3](https://www.php-fig.org/psr/psr-3/), mas também usamos a [PSR 4](https://www.php-fig.org/psr/psr-4/) para o autoload e a [PSR 2](https://www.php-fig.org/psr/psr-2/) no padrão de escrita de código.

O Monolog é uma biblioteca, mas você é livre para utilizá-la se quiser; ela está lá como padrão para facilitar, mas você é livre para implementar `Psr\Log\LoggerInterface` da forma como você quiser.

**Comment by netojoaobatista** [comment]
> eles não irão funcionar caso o desenvolvedor instancie a classe eRede sem uma variável com a instância de LoggerInterface, exemplo:

Na verdade, irão funcionar porque o construtor de `\Rede\eRede` define o parâmetro como opcional; assim, se nada for passado, é utilizado o padrão; mas se for passado algo, é utilizado o que o desenvolvedor escolheu. Por isso os exemplos não precisam ser atualizados; eles funcionam exatamente como antes.

```php
public function __construct(Store $store, LoggerInterface $logger = null)
```
