### ISSUE TITLE
"Unauthorized. Contact issuer." ao autorizar transação

### ISSUE THREAD

**Issue by urameshibr** [DevelopersRede/erede-php#8]
Olá, primeiro quero parabenizar pelo package, código muito bom!

Estou com este problema: 
Peguei o código de exemplo e estou rodando em máquina local com um servidor Laragon (apache) e possuo certificado válido, está retornando esta mensagem abaixo.

"Unauthorized. Contact issuer."

```
try {
        $environment = \Rede\Environment::sandbox();
        $store = new \Rede\Store($credentials['pv'], $credentials['token'], $environment);

        // Transação que será autorizada
        $transaction = (new \Rede\Transaction(20, 'pedido' . time()))
            ->creditCard(
                '5448280000000007',
                '235',
                '12',
                '2020',
                'John Snow'
            );

        // Autoriza a transação
        $transaction = (new \Rede\eRede($store))->create($transaction);
        //...
        // seu código aqui
        } catch (\Rede\Exception\RedeException $e) {
            echo $e->getMessage();
        }
```

**Comment by netojoaobatista** [comment]
Essa mensagem de erro é do autorizador, @urameshibr. Isso significa que a integração ocorreu, os dados foram enviados, mas o autorizador não autorizou a transação. Em produção, quando ocorrer isso, você deve informar ao cliente que a transação dele não foi autorizada e tal.

No ambiente de testes, você consegue fazer testes negativos enviando o valor da venda com o mesmo valor do código de erro da transação. Mas nesse seu caso específico, como o valor não é o mesmo dessa não autorização em questão, você deveria ter uma transação bem sucedida. De fato, fazendo o teste aqui com exatamente seus dados, tive a autorização bem sucedida e um tid retornado.

Esse mensagem ainda persiste para esses dados?

**Comment by urameshibr** [comment]
Oi @netojoaobatista, obrigado por responder, eu fiz o teste e nas primeiras vezes a Rede me retornou esse erro, mas eu recebi retorno com o tid umas 3x, depois voltou a retornar a mensagem de não autorizado.
Fiz uma classe com a finalidade de ser um service, e ter menos código no "html", tanto com a minha classe quanto com o código exemplo o retorno é o mesmo.
Eu vou entrar em contato com eles e resolvendo, volto aqui e deixo a solução (pro meu caso), já serve de ajuda pra alguém com o mesmo problema.

Agradecido!

**Comment by netojoaobatista** [comment]
Cara, isso muito provavelmente é alguma instabilidade no ambiente de testes. Se o mesmo código, horas retorna o TID, horas retorna o não autorizado, muito provavelmente é alguma instabilidade. De qualquer forma, vou deixar a issue aberta.

:smile:

**Comment by urameshibr** [comment]
Resolvido.

Na documentação tem uma lista de cartões de testes pra integração usando o sandbox.
https://www.userede.com.br/desenvolvedores/pt/produto/e-Rede#tutorial-cartao

No menu lateral, "Tutorial playground" > "Cartões de teste", o que único que foi aceito  no meu caso é um chamado "Credz".

Obrigado pela disposição.
