### ISSUE TITLE
Como realizar a venda parcelada ?

### ISSUE THREAD

**Issue by EdcarloLima** [DevelopersRede/erede-php#9]
Tentei da seguinte forma:

$expira = explode('/', $request->expiry);
$dadosCartao = collect();
$dadosCartao->valor = $this->valorFloat($request->valorPagamento);
 // Desta forma deu erro -> $dadosCartao->installments = ['type' => 'zero_interest', 'number' => $request->quantidadeParcela];
 // Desta forma passou a vista ->  $dadosCartao->installments = $request->quantidadeParcela;
$dadosCartao->pedido = $request->alunoCodigo . time();
$dadosCartao->numeroCartao = $this->removerEspacoEmBranco($request->number);
$dadosCartao->numeroVerificador = $request->cvc;
$dadosCartao->expiraMes = trim($expira[0]);
$dadosCartao->expiraAno = trim($expira[1]);
$dadosCartao->titular = $request->name;

 // Autoriza a transação
 $transacao = (new \Rede\eRede($this->redeStore))->create($this->setTransacao($dadosCartao));

**Comment by netojoaobatista** [comment]
O código para autorizar uma transação utilizando o SDK pode ser conferido no README.md, em [Autorizando uma Transação](https://github.com/DevelopersRede/erede-php#autorizando-uma-transa%C3%A7%C3%A3o).

O método para definir o número de parcelas é o `Rede\Transaction::setInstallments`

**Comment by netojoaobatista** [comment]
Mas caso opte por não utilizar o SDK, o manual contém todas as informações necessárias para a integração: [Documentação Transações](https://www.userede.com.br/desenvolvedores/pt/produto/e-Rede#documentacao-transacoes)

**Comment by EdcarloLima** [comment]
Olá @netojoaobatista, então a chamada ao método fica assim:
(new \Rede\Transaction($dados->valor, $dados->pedido))->setInstallments($dados->quantidadeParcelas)->creditCard(
            $dados->numeroCartao,
            $dados->numeroVerificador,
            $dados->expiraMes,
            $dados->expiraAno,
            $dados->titular
        );

**Comment by edicoelho** [comment]
Bom dia, EdCarloLima.
Para maiores informações em relação aos dados, acesse https://www.userede.com.br/desenvolvedores/pt/produto/e-Rede#documentacao
